    ## Configfile
configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/intra_inter.smk"
include: "rules/intra_distance.smk"
include: "rules/network.smk"
include: "rules/enrichment.smk"
include: "rules/assortativity.smk"

wildcard_constraints:
    cutoff="\d+",
    cond="normal|cancer",
    bintype="size|distance|log|onek",
    binsize="\d+",
    ctype="intra|all",
    etype="kegg|onco|ncg",
    commalg="louvain|fgreedy|infomap|leadeigen",
    stat="mean|mean_fitted|median"


rule all:
    input:get_output_files

