################################################################################
## This script performs Kolmogorov-Smirnov (KS) tests to compare the
## distribution of intra-chromosomal interaction fractions between cancer and
## normal samples across different starting thresholds of top MI values.
## Input data is generated by intraInterCount.R.
##
## Inputs:
##   - Fraction table for intra/inter interactions in bins for cancer (from intraInterCount.R)
##   - Fraction table for intra/inter interactions in bins for normal (from intraInterCount.R)
##
## Outputs:
##   - Table of KS test results for each bin (TSV)
################################################################################

log <- file(snakemake@log[[1]], open="wt")
sink(log)
sink(log, type="message")

library(broom)
library(vroom)
library(dplyr)
library(parallel)

MCCORES <- snakemake@threads[[1]]

cat("Reading files \n")
cancer <- vroom::vroom(snakemake@input[["cancer"]])
normal <- vroom::vroom(snakemake@input[["normal"]])

nn <- nrow(cancer)

cat("Performing ", nn, " KS tests\n")
ks_results <- parallel::mclapply(X = 1:nn, FUN = function(i) {
  cat("Test for bin #", i, "\n")
  broom::tidy(ks.test(cancer$intra_fraction[i:nn], normal$intra_fraction[i:nn])) %>%
    mutate(from_bin = cancer$bin[i])
}, mc.cores = MCCORES)

cat("Writing results\n")
bind_rows(ks_results) %>%
  vroom::vroom_write(snakemake@output[[1]])
